name: PHP Composer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite on the compiler
      run: composer run-script phpunit

    - name: Run test suite on the core library
      run: composer run-script test

    - name: Run Psalm
      run: vendor/bin/psalm --threads=2 --output-format=github --shepherd
